// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

package tmt

import (
	"encoding/json"
	"fmt"
)

// renderRuncmdsPlugin returns the Python source for the TMT_PLUGINS file that injects
// the configured cloud-init runcmd commands. The commands are JSON-encoded so they
// round-trip safely as Python string literals (JSON strings are a subset of Python's),
// avoiding any code-injection risk from caller-supplied configuration.
//
// At tmt startup, this file is loaded by tmt's plugin loader (when TMT_PLUGINS points
// at its parent directory). The module-level loop appends each command to
// `tmt.steps.provision.testcloud.TESTCLOUD_WORKAROUNDS`, which tmt reads when
// constructing the cloud-init user-data for a testcloud guest. testcloud writes those
// commands into the `runcmd:` block of the cloud-config — they execute on the guest's
// first boot, before the testcloud HTTP probe service starts.
func renderRuncmdsPlugin(runcmds []string) (string, error) {
	jsonBytes, err := json.Marshal(runcmds)
	if err != nil {
		return "", fmt.Errorf("failed to marshal runcmds:\n%w", err)
	}

	return fmt.Sprintf(`# Generated by azldev. Do not edit.
#
# This file is loaded by tmt at startup via the TMT_PLUGINS environment variable
# (see tmt/plugins/__init__.py:_explore_custom_directories). Module-level code runs
# before any tmt step, so by the time the provision step builds its cloud-init data,
# our entries are already in the TESTCLOUD_WORKAROUNDS list.
#
# Each entry is a shell command that runs during cloud-init runcmd on the guest,
# *before* testcloud.service starts the boot-complete HTTP probe.

import tmt.steps.provision.testcloud as _tc

_AZLDEV_RUNCMDS = %s

for _cmd in _AZLDEV_RUNCMDS:
    _tc.TESTCLOUD_WORKAROUNDS.append(_cmd)
`, string(jsonBytes)), nil
}
