// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

package sources

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"path/filepath"
	"slices"
	"strings"
	"time"
	"unicode"

	gogit "github.com/go-git/go-git/v5"
	"github.com/go-git/go-git/v5/plumbing/filemode"
	"github.com/go-git/go-git/v5/plumbing/object"
	"github.com/microsoft/azure-linux-dev-tools/internal/app/azldev/core/components"
	"github.com/microsoft/azure-linux-dev-tools/internal/global/opctx"
	"github.com/microsoft/azure-linux-dev-tools/internal/lockfile"
	"github.com/microsoft/azure-linux-dev-tools/internal/projectconfig"
	"github.com/microsoft/azure-linux-dev-tools/internal/providers/sourceproviders"
	"github.com/microsoft/azure-linux-dev-tools/internal/providers/sourceproviders/fedorasource"
	"github.com/microsoft/azure-linux-dev-tools/internal/utils/dirdiff"
	"github.com/microsoft/azure-linux-dev-tools/internal/utils/fileperms"
	"github.com/microsoft/azure-linux-dev-tools/internal/utils/fileutils"
	"github.com/samber/lo"
)

// MacrosFileExtension is the file extension used for azldev-generated macros files.
const MacrosFileExtension = ".azl.macros"

// MacrosFileHeader is the comment header included at the top of generated macros files.
const MacrosFileHeader = `# Macros file automatically generated by azldev.
# Do not edit manually; changes will be overwritten.`

// SourcePreparer is a utility for acquiring and preparing all input files required to build a component.
// This may include the component's spec file, any loose files that must accompany it, any payload source
// archives and patches required by the spec, etc. Preparation may also include any post-processing of these
// inputs to match the component's configuration within the containing project.
type SourcePreparer interface {
	// PrepareSources prepares the input sources for the given component, writing them to the given output directory.
	// After this function completes successfully, the output directory should contain all files required to build
	// the component, with any post-processing applied as necessary. The only remaining dependencies not contained
	// within the output directory will be build-time dependencies on external packages (RPMs), including those
	// relied on to be present implicitly within the build root, or expressed via BuildRequires or DynamicBuildRequires
	// in the component's spec file and any defaults from the macros used to interpret the spec file.
	PrepareSources(ctx context.Context, component components.Component, outputDir string, applyOverlays bool) error

	// DiffSources computes a unified diff showing the changes that overlays apply to a component's sources.
	// The component's sources are fetched once into a subdirectory of baseDir, then copied to a second
	// subdirectory where overlays are applied in-place. The diff between the two subdirectories is returned.
	DiffSources(ctx context.Context, component components.Component, baseDir string) (*dirdiff.DiffResult, error)
}

// PreparerOption is a functional option for configuring a [SourcePreparer].
type PreparerOption func(*sourcePreparerImpl)

// WithGitRepo returns a [PreparerOption] that enables dist-git repository
// creation during source preparation. When set, the upstream .git directory
// is preserved and synthetic commit history is generated on top of it. This
// requires the project configuration to reside inside a git repository.
// Without this option, no dist-git is created and synthetic history is skipped.
//
// The cmdFactory is used to shell out to git for fingerprint change detection.
// The lockReader provides access to per-component lock files and their directory.
func WithGitRepo(
	cmdFactory opctx.CmdFactory,
	lockReader lockfile.LockReader,
) PreparerOption {
	return func(p *sourcePreparerImpl) {
		p.withGitRepo = true
		p.cmdFactory = cmdFactory
		p.lockReader = lockReader
	}
}

// WithSkipLookaside returns a [PreparerOption] that skips all lookaside cache
// downloads during source preparation. This includes both explicit source file
// downloads ([SourceManager.FetchFiles]) and lookaside extraction during
// component fetching ([FedoraSourceDownloader.ExtractSourcesFromRepo]).
// Git-tracked files (spec, patches, scripts, configs) are still fetched from
// the upstream clone. This is useful for rendering, where only the spec and
// sidecar files are needed and downloading large source tarballs is unnecessary.
func WithSkipLookaside() PreparerOption {
	return func(p *sourcePreparerImpl) {
		p.skipLookaside = true
	}
}

// WithAllowNoHashes returns a [PreparerOption] that allows source file
// references to omit their [projectconfig.SourceFileReference.Hash] value.
// When set, any source file that lacks a hash will have its hash computed
// from the already-downloaded file in the output directory. If
// [projectconfig.SourceFileReference.HashType] is also missing, SHA-512 is
// used as the default. A warning is emitted for each file whose hash is
// auto-computed.
//
// When combined with [WithSkipLookaside], source file downloads are skipped,
// so files needed for hash computation are not available on disk. In that
// case, missing hashes cannot be auto-computed and source preparation
// returns an error.
func WithAllowNoHashes() PreparerOption {
	return func(p *sourcePreparerImpl) {
		p.allowNoHashes = true
	}
}

// Standard implementation of the [SourcePreparer] interface.
type sourcePreparerImpl struct {
	sourceManager sourceproviders.SourceManager
	fs            opctx.FS
	eventListener opctx.EventListener
	dryRunnable   opctx.DryRunnable

	// withGitRepo, when true, enables dist-git creation by preserving the
	// upstream .git directory and generating synthetic commit history.
	withGitRepo bool

	// skipLookaside, when true, skips all lookaside cache downloads during
	// source preparation. Git-tracked files are still fetched.
	skipLookaside bool

	// cmdFactory is used to shell out to git for fingerprint change detection
	// in the project repository. Set via [WithGitRepo].
	cmdFactory opctx.CmdFactory

	// lockReader provides access to per-component lock files and their
	// directory path. Set via [WithGitRepo].
	lockReader lockfile.LockReader

	// allowNoHashes, when true, allows source file references without hash
	// values. Missing hashes are computed from the downloaded files.
	allowNoHashes bool
}

// NewPreparer creates a new [SourcePreparer] instance. All positional arguments
// are required. Optional behavior can be configured via [PreparerOption] values.
func NewPreparer(
	sourceManager sourceproviders.SourceManager,
	fs opctx.FS,
	eventListener opctx.EventListener,
	dryRunnable opctx.DryRunnable,
	opts ...PreparerOption,
) (SourcePreparer, error) {
	if sourceManager == nil {
		return nil, errors.New("source manager cannot be nil")
	}

	if fs == nil {
		return nil, errors.New("filesystem interface cannot be nil")
	}

	if eventListener == nil {
		return nil, errors.New("event listener interface cannot be nil")
	}

	if dryRunnable == nil {
		return nil, errors.New("dry runnable interface cannot be nil")
	}

	impl := &sourcePreparerImpl{
		sourceManager: sourceManager,
		fs:            fs,
		eventListener: eventListener,
		dryRunnable:   dryRunnable,
	}

	for _, opt := range opts {
		if opt != nil {
			opt(impl)
		}
	}

	return impl, nil
}

// PrepareSources implements the [SourcePreparer] interface.
func (p *sourcePreparerImpl) PrepareSources(
	ctx context.Context, component components.Component, outputDir string, applyOverlays bool,
) error {
	// Use the source manager to fetch source files (archives, patches, etc.)
	// Skip this step when skipLookaside is set — source tarballs are not needed
	// for rendering and are the most expensive download.
	if !p.skipLookaside {
		err := p.sourceManager.FetchFiles(ctx, component, outputDir)
		if err != nil {
			return fmt.Errorf("failed to fetch source files for component %#q:\n%w",
				component.GetName(), err)
		}
	}

	// Preserve the upstream .git directory only when dist-git creation is
	// requested via --with-git. This is required so that overlay commits can be
	// appended on top of the upstream commit log during synthetic history generation.
	var fetchOpts []sourceproviders.FetchComponentOption
	if applyOverlays && p.withGitRepo {
		fetchOpts = append(fetchOpts, sourceproviders.WithPreserveGitDir())
	}

	if p.skipLookaside {
		fetchOpts = append(fetchOpts, sourceproviders.WithSkipLookaside())
	}

	// Use the source manager to fetch the component (spec file and sidecar files).
	err := p.sourceManager.FetchComponent(ctx, component, outputDir, fetchOpts...)
	if err != nil {
		return fmt.Errorf("failed to fetch sources for component %#q:\n%w",
			component.GetName(), err)
	}

	if applyOverlays {
		err := p.applyOverlaysToSources(ctx, component, outputDir)
		if err != nil {
			return err
		}

		if err := p.updateSourcesFile(component, outputDir); err != nil {
			return fmt.Errorf("failed to update 'sources' file for component %#q:\n%w",
				component.GetName(), err)
		}
	} else {
		slog.Warn("Sources prepared without applying overlays;"+
			" 'sources' file will not include entries from the 'source-files' configuration",
			"component", component.GetName())
	}

	// Record the changes as synthetic git history when dist-git creation is enabled.
	if p.withGitRepo {
		if err := p.trySyntheticHistory(ctx, component, outputDir); err != nil {
			return fmt.Errorf("failed to generate synthetic history for component %#q:\n%w",
				component.GetName(), err)
		}
	}

	return nil
}

// applyOverlaysToSources writes the macros file and then applies all overlays.
func (p *sourcePreparerImpl) applyOverlaysToSources(
	ctx context.Context, component components.Component, outputDir string,
) error {
	// Emit computed macros to a macros file in the output directory.
	// If the build configuration produces no macros, no file is written and
	// macrosFileName will be empty.
	var macrosFileName string

	macrosFilePath, err := p.writeMacrosFile(component, outputDir)
	if err != nil {
		return fmt.Errorf("failed to write macros file for component %#q:\n%w",
			component.GetName(), err)
	}

	if macrosFilePath != "" {
		macrosFileName = filepath.Base(macrosFilePath)
	}

	// Apply all overlays to prepared sources.
	if err := p.applyOverlays(ctx, component, outputDir, macrosFileName); err != nil {
		return fmt.Errorf("failed to apply overlays for component %#q:\n%w", component.GetName(), err)
	}

	return nil
}

// applyOverlays applies all overlays (user-defined and system-generated) to the
// component sources. Overlay application is decoupled from git history generation:
// overlays modify the working tree; synthetic history is recorded separately by
// [trySyntheticHistory].
func (p *sourcePreparerImpl) applyOverlays(
	_ context.Context, component components.Component, sourcesDirPath, macrosFileName string,
) error {
	event := p.eventListener.StartEvent("Applying overlays", "component", component.GetName())
	defer event.End()

	// Resolve the spec path once for all overlay operations in this call.
	absSpecPath, err := p.resolveSpecPath(component, sourcesDirPath)
	if err != nil {
		return err
	}

	// Collect all overlays in application order. This ensures every change is
	// captured in the synthetic history, including build configuration changes.
	allOverlays, err := p.collectOverlays(component, macrosFileName)
	if err != nil {
		return fmt.Errorf("failed to collect overlays for component %#q:\n%w", component.GetName(), err)
	}

	if len(allOverlays) == 0 {
		return nil
	}

	// Apply all overlays to the working tree.
	if err := p.applyOverlayList(allOverlays, sourcesDirPath, absSpecPath); err != nil {
		return fmt.Errorf("failed to apply overlays for component %#q:\n%w", component.GetName(), err)
	}

	return nil
}

// collectOverlays gathers all overlays for a component into a single ordered slice:
// macros-load first, then user overlays, followed by check-skip and file-header overlays.
func (p *sourcePreparerImpl) collectOverlays(
	component components.Component, macrosFileName string,
) ([]projectconfig.ComponentOverlay, error) {
	config := component.GetConfig()

	var allOverlays []projectconfig.ComponentOverlay

	if macrosFileName != "" || len(config.Build.Undefines) > 0 {
		macroOverlays, err := synthesizeMacroLoadOverlays(macrosFileName, config.Build.Undefines)
		if err != nil {
			return nil, fmt.Errorf("failed to compute macros load overlays:\n%w", err)
		}

		allOverlays = append(allOverlays, macroOverlays...)
	}

	allOverlays = append(allOverlays, config.Overlays...)
	allOverlays = append(allOverlays, synthesizeCheckSkipOverlays(config.Build.Check)...)
	allOverlays = append(allOverlays, generateFileHeaderOverlay()...)

	return allOverlays, nil
}

// initSourcesRepo initializes a new git repository in sourcesDirPath, stages all files,
// and creates an initial commit. This is used for components that don't have an upstream
// dist-git so that synthetic commits can still be layered on top.
func initSourcesRepo(sourcesDirPath string) (*gogit.Repository, error) {
	slog.Info("Initializing git repository for sources", "path", sourcesDirPath)

	repo, err := gogit.PlainInit(sourcesDirPath, false)
	if err != nil {
		return nil, fmt.Errorf("failed to initialize git repository at %#q:\n%w", sourcesDirPath, err)
	}

	worktree, err := repo.Worktree()
	if err != nil {
		return nil, fmt.Errorf("failed to get worktree:\n%w", err)
	}

	if err := worktree.AddWithOptions(&gogit.AddOptions{All: true}); err != nil {
		return nil, fmt.Errorf("failed to stage files:\n%w", err)
	}

	_, err = worktree.Commit("Initial sources", &gogit.CommitOptions{
		Author: &object.Signature{
			Name: "azldev",
			When: time.Unix(0, 0).UTC(),
		},
	})
	if err != nil {
		return nil, fmt.Errorf("failed to create initial commit:\n%w", err)
	}

	return repo, nil
}

// trySyntheticHistory attempts to create synthetic git commits on top of the
// component's sources directory. Synthetic commits are derived from lock file
// fingerprint changes in the project repository and interleaved into the
// upstream dist-git history. If no .git directory exists, one is initialized
// with an initial commit so synthetic commits can be layered on uniformly.
//
// Returns a non-nil error if history generation fails.
func (p *sourcePreparerImpl) trySyntheticHistory(
	ctx context.Context,
	component components.Component,
	sourcesDirPath string,
) error {
	config := component.GetConfig()
	componentName := component.GetName()

	// Build commit metadata from lock file fingerprint changes.
	changes, importCommit, err := buildSyntheticCommits(
		ctx, p.cmdFactory, config, componentName, p.lockReader.LockDir(),
	)
	if err != nil {
		return fmt.Errorf("failed to build synthetic commits:\n%w", err)
	}

	if len(changes) == 0 {
		slog.Debug("No synthetic commits to create; skipping history generation",
			"component", componentName)

		return nil
	}

	// Adjust the Release tag before staging changes. See [tryBumpStaticRelease]
	// for the handling of %autorelease, static integers, and non-standard values.
	if err := p.tryBumpStaticRelease(component, sourcesDirPath, len(changes)); err != nil {
		return fmt.Errorf("failed to apply release bump:\n%w", err)
	}

	gitDirPath := filepath.Join(sourcesDirPath, ".git")

	gitDirExists, err := fileutils.Exists(p.fs, gitDirPath)
	if err != nil {
		return fmt.Errorf("failed to check for .git directory at %#q:\n%w", gitDirPath, err)
	}

	if !gitDirExists {
		slog.Info("No .git directory in sources; initializing repository",
			"component", componentName)

		if _, err := initSourcesRepo(sourcesDirPath); err != nil {
			return fmt.Errorf("failed to initialize sources repository:\n%w", err)
		}
	}

	// Open the git repository where synthetic commits will be recorded.
	sourcesRepo, err := gogit.PlainOpen(sourcesDirPath)
	if err != nil {
		return fmt.Errorf("failed to open sources repository at %#q:\n%w", sourcesDirPath, err)
	}

	// Strip bogus submodule entries from the index before staging. Some upstream
	// repos have gitlink entries without .gitmodules that break go-git's staging.
	if err := removeSubmoduleEntries(p.fs, sourcesRepo, sourcesDirPath); err != nil {
		return fmt.Errorf("failed to remove submodule entries:\n%w", err)
	}

	if err := CommitInterleavedHistory(sourcesRepo, changes, importCommit); err != nil {
		return fmt.Errorf("failed to commit synthetic history:\n%w", err)
	}

	return nil
}

// removeSubmoduleEntries strips gitlink (mode 160000) entries from the repository
// index and removes the corresponding empty directories from disk. Some upstream
// dist-git repositories (e.g., Fedora's "at" package) contain bogus submodule
// references — gitlink entries without a .gitmodules file — that leave empty
// directories after cloning. go-git's [gogit.Worktree.AddWithOptions] fails when
// it encounters these because it tries to read the directory path as a file.
func removeSubmoduleEntries(fs opctx.FS, repo *gogit.Repository, repoDir string) error {
	idx, err := repo.Storer.Index()
	if err != nil {
		return fmt.Errorf("failed to read git index:\n%w", err)
	}

	originalLen := len(idx.Entries)
	kept := 0

	for _, entry := range idx.Entries {
		if entry.Mode == filemode.Submodule {
			slog.Info("Removing bogus submodule entry from index",
				"path", entry.Name)

			// Remove the directory left by the uninitialized submodule.
			if removeErr := fs.RemoveAll(filepath.Join(repoDir, entry.Name)); removeErr != nil {
				slog.Warn("Failed to remove submodule directory",
					"path", entry.Name, "error", removeErr)
			}

			continue
		}

		idx.Entries[kept] = entry
		kept++
	}

	if kept == originalLen {
		return nil
	}

	idx.Entries = idx.Entries[:kept]

	if err := repo.Storer.SetIndex(idx); err != nil {
		return fmt.Errorf("failed to update git index:\n%w", err)
	}

	slog.Info("Removed submodule entries from git index",
		"count", originalLen-kept)

	return nil
}

// DiffSources implements the [SourcePreparer] interface.
// It fetches the component's sources once, copies them to a second directory, applies overlays
// to the copy, then diffs the two trees. This avoids fetching the sources twice.
func (p *sourcePreparerImpl) DiffSources(
	ctx context.Context, component components.Component, baseDir string,
) (result *dirdiff.DiffResult, err error) {
	event := p.eventListener.StartEvent("Computing overlay diff", "component", component.GetName())
	defer event.End()

	// Create temp dirs for sources prepared without and with overlays.
	originalDir, err := fileutils.MkdirTemp(p.fs, baseDir, "original-")
	if err != nil {
		return nil, fmt.Errorf("failed to create temp dir for original sources:\n%w", err)
	}

	defer fileutils.RemoveAllAndUpdateErrorIfNil(p.fs, originalDir, &err)

	// Prepare sources without applying overlays, to get the original tree.
	if err := p.PrepareSources(ctx, component, originalDir, false /* applyOverlays */); err != nil {
		return nil, err
	}

	// Copy the fetched sources to a separate directory for in-place overlay application.
	// This avoids a second network fetch.
	overlaidDir, err := fileutils.MkdirTemp(p.fs, baseDir, "overlaid-")
	if err != nil {
		return nil, fmt.Errorf("failed to create temp dir for overlaid sources:\n%w", err)
	}

	defer fileutils.RemoveAllAndUpdateErrorIfNil(p.fs, overlaidDir, &err)

	if err := fileutils.CopyDirRecursive(
		p.dryRunnable, p.fs, originalDir, overlaidDir,
		fileutils.CopyDirOptions{CopyFileOptions: fileutils.CopyFileOptions{PreserveFileMode: true}},
	); err != nil {
		return nil, fmt.Errorf("failed to copy sources for component %#q:\n%w", component.GetName(), err)
	}

	// Apply overlays in-place to the copied directory only.
	if err := p.applyOverlaysToSources(ctx, component, overlaidDir); err != nil {
		return nil, fmt.Errorf("failed to apply overlays for component %#q:\n%w", component.GetName(), err)
	}

	// Diff the original tree against the overlaid tree.
	result, err = dirdiff.DiffDirs(p.fs, originalDir, overlaidDir)
	if err != nil {
		return nil, fmt.Errorf("failed to diff source trees for component %#q:\n%w",
			component.GetName(), err)
	}

	return result, nil
}

// updateSourcesFile appends entries to the 'sources' file for any extra source files
// defined in the component's [projectconfig.SourceFileReference] configuration. Each source file reference
// must have both [projectconfig.SourceFileReference.Hash] and [projectconfig.SourceFileReference.HashType]
// specified unless [sourcePreparerImpl.allowNoHashes] is set, in which case
// missing hashes are computed from the downloaded files in outputDir.
// Conflicts between existing entries in the 'sources' file and sources introduced through
// the [projectconfig.SourceFileReference] configuration are also treated as errors.
func (p *sourcePreparerImpl) updateSourcesFile(component components.Component, outputDir string) error {
	sourceFiles := component.GetConfig().SourceFiles
	if len(sourceFiles) == 0 {
		return nil
	}

	sourcesFilePath := filepath.Join(outputDir, fedorasource.SourcesFileName)

	existingContent, err := p.readSourcesFileIfExists(sourcesFilePath)
	if err != nil {
		return err
	}

	existingEntries, err := fedorasource.ReadSourcesFileEntries(existingContent)
	if err != nil {
		return fmt.Errorf("failed to parse existing sources file %#q:\n%w", sourcesFilePath, err)
	}

	existingFilenames := make(map[string]bool, len(existingEntries))
	for _, entry := range existingEntries {
		if existingFilenames[entry.Filename] {
			return fmt.Errorf(
				"failed to process existing 'sources' file %#q: duplicate filename %#q",
				sourcesFilePath, entry.Filename)
		}

		existingFilenames[entry.Filename] = true
	}

	newEntries, err := p.buildSourceEntries(sourceFiles, existingFilenames, component.GetName(), outputDir)
	if err != nil {
		return err
	}

	// Ensure existing content ends with a newline before appending.
	if existingContent != "" && !strings.HasSuffix(existingContent, "\n") {
		existingContent += "\n"
	}

	newContent := existingContent + strings.Join(newEntries, "\n") + "\n"

	if err := fileutils.WriteFile(
		p.fs,
		sourcesFilePath,
		[]byte(newContent),
		fileperms.PublicFile,
	); err != nil {
		return fmt.Errorf("failed to write sources file %#q:\n%w", sourcesFilePath, err)
	}

	slog.Info("Updated sources file with extra source file entries",
		"count", len(newEntries),
		"path", sourcesFilePath)

	return nil
}

// readSourcesFileIfExists reads the sources file content if it exists, returning empty string if not.
func (p *sourcePreparerImpl) readSourcesFileIfExists(sourcesFilePath string) (string, error) {
	exists, err := fileutils.Exists(p.fs, sourcesFilePath)
	if err != nil {
		return "", fmt.Errorf("failed to check if sources file %#q exists:\n%w", sourcesFilePath, err)
	}

	if !exists {
		return "", nil
	}

	data, err := fileutils.ReadFile(p.fs, sourcesFilePath)
	if err != nil {
		return "", fmt.Errorf("failed to read sources file %#q:\n%w", sourcesFilePath, err)
	}

	return string(data), nil
}

// buildSourceEntries validates [projectconfig.SourceFileReference] and collects formatted entries.
// When [sourcePreparerImpl.allowNoHashes] is true, missing hashes are computed from the downloaded files
// in [outputDir]. When [sourcePreparerImpl.skipLookaside] is also true, hash computation is skipped
// because the source files were not downloaded.
func (p *sourcePreparerImpl) buildSourceEntries(
	sourceFiles []projectconfig.SourceFileReference,
	existingFilenames map[string]bool,
	componentName string,
	outputDir string,
) ([]string, error) {
	newEntries := make([]string, 0, len(sourceFiles))

	for _, ref := range sourceFiles {
		if err := fileutils.ValidateFilename(ref.Filename); err != nil {
			return nil, fmt.Errorf("invalid filename %#q in 'source-files' configuration:\n%w", ref.Filename, err)
		}

		if existingFilenames[ref.Filename] {
			return nil, fmt.Errorf(
				"source file %#q in 'source-files' configuration conflicts with an existing entry in the 'sources' file; "+
					"to overwrite the existing entry, ensure it's removed first; "+
					"if this is unintentional, use a different filename",
				ref.Filename)
		}

		hash, hashType, err := p.resolveSourceHash(ref, componentName, outputDir)
		if err != nil {
			return nil, err
		}

		entry := fedorasource.FormatSourcesEntry(ref.Filename, hashType, hash)
		newEntries = append(newEntries, entry)

		slog.Debug("New 'sources' file entry",
			"filename", ref.Filename,
			"hashType", hashType,
			"hash", hash)
	}

	return newEntries, nil
}

// resolveSourceHash returns the hash and hash type for a source file reference.
// If the reference already has both values, they are returned as-is. When [ref.Hash]
// is missing and '--allow-no-hashes' is set, the hash is computed from the
// downloaded file on disk. Returns an error when the hash cannot be resolved.
func (p *sourcePreparerImpl) resolveSourceHash(
	ref projectconfig.SourceFileReference, componentName string, outputDir string,
) (hash string, hashType fileutils.HashType, err error) {
	hash = ref.Hash
	hashType = ref.HashType

	if hash != "" {
		if hashType == "" {
			return "", "", fmt.Errorf(
				"source file %#q has a 'hash' value but no 'hash-type'; "+
					"both must be specified in the 'source-files' configuration;"+
					"alternatively 'hash' can be omitted and 'prep-sources' run with "+
					"'--allow-no-hashes' to compute missing hashes automatically",
				ref.Filename)
		}

		return hash, hashType, nil
	}

	// Hash is empty — resolve it if '--allow-no-hashes' is set.
	if !p.allowNoHashes {
		return "", "", fmt.Errorf(
			"source file %#q is missing required 'hash'; specify the hash in the "+
				"'source-files' configuration or use '--allow-no-hashes' to compute it automatically",
			ref.Filename)
	}

	if p.skipLookaside {
		return "", "", fmt.Errorf(
			"source file %#q is missing its hash and source file downloads were skipped; "+
				"hash cannot be computed without the downloaded file",
			ref.Filename)
	}

	if hashType == "" {
		hashType = fileutils.HashTypeSHA512

		slog.Warn("No 'hash-type' specified for source file; defaulting to SHA-512",
			"component", componentName,
			"filename", ref.Filename,
			"hashType", hashType)
	}

	filePath := filepath.Join(outputDir, ref.Filename)

	hash, err = fileutils.ComputeFileHash(p.fs, hashType, filePath)
	if err != nil {
		return "", "", fmt.Errorf("failed to compute hash for source file %#q:\n%w",
			ref.Filename, err)
	}

	slog.Warn("Auto-computed hash for source file; consider adding 'hash' to the configuration",
		"component", componentName,
		"filename", ref.Filename,
		"hashType", hashType,
		"hash", hash)

	return hash, hashType, nil
}

// writeMacrosFile writes a macros file containing the resolved macros for a component.
// This includes with/without flags converted to macro format, and any explicit defines.
// If the build configuration produces no macros, no file is written and an empty path is
// returned. Otherwise, the path to the written macros file is returned.
func (p *sourcePreparerImpl) writeMacrosFile(component components.Component, outputDir string) (string, error) {
	contents := GenerateMacrosFileContents(component.GetConfig().Build)
	if contents == "" {
		return "", nil
	}

	macrosFilePath := filepath.Join(outputDir, component.GetName()+MacrosFileExtension)

	err := fileutils.WriteFile(p.fs, macrosFilePath, []byte(contents), fileperms.PublicFile)
	if err != nil {
		return "", fmt.Errorf("failed to write macros file %#q:\n%w", macrosFilePath, err)
	}

	return macrosFilePath, nil
}

// GenerateMacrosFileContents generates the contents of an RPM macros file from the given
// build configuration. The output uses standard RPM macro file format (%name value) and
// includes a header comment identifying the file as auto-generated.
//
// With flags are converted to %_with_FLAG 1 macros.
// Without flags are converted to %_without_FLAG 1 macros.
// Defines are emitted as %name value macros.
//
// All macros are collected into a single map and sorted alphabetically by name for
// deterministic output. If the same macro is defined multiple times (e.g., via both
// a with flag and an explicit define), the later definition wins. The order of processing
// is: with flags, then without flags, then explicit defines, then undefines.
//
// Undefines are processed in two complementary places:
//
//  1. In this function, an undefine removes the same-named entry from the locally-built
//     map so we never emit a `%name value` line in this file that would conflict with
//     a paired undefine. (RPM's macros file format does NOT accept the `%undefine`
//     directive itself — `%{load:...}` parses each line as `%name body`, and treating
//     `undefine` as a macro name conflicts with the builtin. So this file CANNOT
//     carry the actual undefine.)
//  2. The actual `%undefine NAME` directives are emitted directly into the spec via
//     [synthesizeMacroLoadOverlays], which prepends them to the spec immediately
//     after the `%{load:...}` of this file. That defeats any macro of that name
//     defined by the chroot environment, distro setup, or any other RPM macro source.
//
// Note: RPM macro values can contain spaces without special escaping; everything
// after the macro name (and separating whitespace) is treated as the macro body.
//
// If no macros remain after processing (empty config, or all macros removed via
// undefines), an empty string is returned to signal that no macros file is needed.
// Note: in that case the caller is still responsible for emitting any `%undefine`
// overlays for the spec — see [synthesizeMacroLoadOverlays].
func GenerateMacrosFileContents(buildConfig projectconfig.ComponentBuildConfig) string {
	// Build a unified map of all macros. Later definitions override earlier ones.
	// Processing order: with flags -> without flags -> explicit defines.
	macros := make(map[string]string)

	// Convert 'with' flags to macros: FLAG -> _with_FLAG = 1
	for _, with := range buildConfig.With {
		macros["_with_"+with] = "1"
	}

	// Convert 'without' flags to macros: FLAG -> _without_FLAG = 1
	for _, without := range buildConfig.Without {
		macros["_without_"+without] = "1"
	}

	// Add explicit macro definitions (these override any conflicting with/without flags).
	for name, value := range buildConfig.Defines {
		macros[name] = value
	}

	// Remove from the local map any macros listed in undefines so we never emit
	// a `%name value` line in this file that contradicts the spec-level
	// `%undefine NAME` emitted by [synthesizeMacroLoadOverlays].
	for _, undef := range buildConfig.Undefines {
		delete(macros, undef)
	}

	if len(macros) == 0 {
		return ""
	}

	lines := []string{
		MacrosFileHeader,
	}

	// Sort macro names for deterministic output.
	macroNames := lo.Keys(macros)
	slices.Sort(macroNames)

	for _, name := range macroNames {
		lines = append(lines, fmt.Sprintf("%%%s %s", name, macros[name]))
	}

	return strings.Join(lines, "\n") + "\n"
}

// synthesizeMacroLoadOverlays produces overlays that:
//
//  1. (When macrosFileName is non-empty) Inject a `%{load:...}` directive at the
//     top of the spec to pull in the azldev-generated macros file, and register
//     the macros file as Source9999 so mock and other tools include it in the
//     build root.
//  2. (When undefines is non-empty) Inject explicit `%undefine NAME` directives
//     directly into the spec for every entry in undefines.
//
// The `%undefine` directive removes the named macro from RPM's global macro
// context, defeating any definition from the chroot environment, distro setup,
// installed package macros, or anywhere else. This is the only way `undefines`
// can take effect against external macros, because RPM's macros-file format
// (used by `%{load:...}`) does NOT accept `%undefine` itself — it parses every
// non-comment line as `%name body`, treating `undefine` as a macro name, which
// conflicts with the builtin.
//
// At least one of macrosFileName or undefines must be non-empty for this
// function to produce any overlays.
func synthesizeMacroLoadOverlays(
	macrosFileName string, undefines []string,
) ([]projectconfig.ComponentOverlay, error) {
	// Sort and deduplicate undefines for deterministic output.
	undefNames := slices.Clone(undefines)
	slices.Sort(undefNames)
	undefNames = slices.Compact(undefNames)

	if macrosFileName == "" && len(undefNames) == 0 {
		return nil, nil
	}

	var (
		prependLines []string
		overlays     []projectconfig.ComponentOverlay
	)

	if macrosFileName != "" {
		// Basic check that the macros file name is valid and doesn't require escaping.
		if strings.ContainsFunc(macrosFileName, func(r rune) bool {
			return !unicode.IsLetter(r) && !unicode.IsDigit(r) && r != '.' && r != '-' && r != '_' && r != '+'
		}) {
			return nil, fmt.Errorf(
				"macros file name %#q contains invalid characters; does the component name contain invalid characters?",
				macrosFileName,
			)
		}

		prependLines = append(prependLines,
			"# All Azure Linux specs with overlays include this macro file, irrespective of"+
				" whether new macros have been added.",
			fmt.Sprintf("%%{load:%%{_sourcedir}/%s}", macrosFileName),
		)
	}

	if len(undefNames) > 0 {
		// `%undefine` is a spec-level directive and can only be emitted into the spec
		// directly (not into the macros file loaded via `%{load:...}`). Emitting these
		// after the load directive (when present) makes the rendered spec
		// self-documenting about which inherited macros are being suppressed.
		prependLines = append(prependLines,
			"# Forcibly undefine inherited RPM macros listed in build.undefines.")
		for _, name := range undefNames {
			prependLines = append(prependLines, fmt.Sprintf("%%undefine %s", name))
		}
	}

	prependLines = append(prependLines, "")
	overlays = append(overlays, projectconfig.ComponentOverlay{
		Type:  projectconfig.ComponentOverlayPrependSpecLines,
		Lines: prependLines,
	})

	if macrosFileName != "" {
		overlays = append(overlays, projectconfig.ComponentOverlay{
			// Ensure that the macros file is manifested as a source in the spec so that
			// mock and other tools know it needs to be present in the build root.
			// Use InsertSpecTag to place it after the last existing Source* tag, avoiding
			// misplacement after macros like %fontpkg or inside %if conditionals.
			Type:  projectconfig.ComponentOverlayInsertSpecTag,
			Tag:   "Source9999", // Use a high number to avoid conflicts with existing sources.
			Value: macrosFileName,
		})
	}

	return overlays, nil
}

// generateFileHeaderOverlay generates an overlay that prepends a header to the spec.
// It should be applied after all other overlays, as it should be the first thing in the spec file.
func generateFileHeaderOverlay() []projectconfig.ComponentOverlay {
	return []projectconfig.ComponentOverlay{
		{
			Type: projectconfig.ComponentOverlayPrependSpecLines,
			Lines: []string{
				"# This spec file has been modified by azldev to include build configuration overlays.",
				"# Do not edit manually; changes may be overwritten.",
				"",
			},
		},
	}
}

// synthesizeCheckSkipOverlays generates overlays to disable the %check section if configured.
// When check.skip is true, it prepends an 'exit 0' to the %check section with a comment
// explaining why the section was disabled.
func synthesizeCheckSkipOverlays(checkConfig projectconfig.CheckConfig) []projectconfig.ComponentOverlay {
	if !checkConfig.Skip {
		return nil
	}

	return []projectconfig.ComponentOverlay{
		{
			Type:        projectconfig.ComponentOverlayPrependSpecLines,
			SectionName: "%check",
			Lines: []string{
				"# Check section disabled: " + checkConfig.SkipReason,
				"exit 0",
				"",
			},
		},
	}
}

// resolveSpecPath locates and returns the absolute path to the component's spec file
// within the given sources directory.
func (p *sourcePreparerImpl) resolveSpecPath(
	component components.Component, sourcesDirPath string,
) (string, error) {
	specPath, err := findSpecInDir(p.fs, component, sourcesDirPath)
	if err != nil {
		return "", fmt.Errorf("failed to find spec in sources dir %#q:\n%w", sourcesDirPath, err)
	}

	absSpecPath, err := filepath.Abs(specPath)
	if err != nil {
		return "", fmt.Errorf("failed to get absolute path for spec %#q:\n%w", specPath, err)
	}

	return absSpecPath, nil
}

// applyOverlayList applies a list of overlays to the component sources sequentially.
func (p *sourcePreparerImpl) applyOverlayList(
	overlays []projectconfig.ComponentOverlay, sourcesDirPath, absSpecPath string,
) error {
	for _, overlay := range overlays {
		if err := ApplyOverlayToSources(
			p.dryRunnable, p.fs, overlay, sourcesDirPath, absSpecPath,
		); err != nil {
			return fmt.Errorf("failed to apply %#q overlay:\n%w", overlay.Type, err)
		}
	}

	return nil
}

func findSpecInDir(
	fs opctx.FS, component components.Component, dirPath string,
) (string, error) {
	specPath := filepath.Join(dirPath, component.GetName()+".spec")

	if _, statErr := fs.Stat(specPath); statErr != nil {
		return specPath, fmt.Errorf("failed to find spec for component %#q in %#q:\n%w",
			component.GetName(), dirPath, statErr,
		)
	}

	return specPath, nil
}
